"""add createdAt and type to motion files

Revision ID: 5adae1e9672d
Revises: 856817febc15
Create Date: 2025-04-02 15:59:31.205065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adae1e9672d'
down_revision = '856817febc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motion_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motion_files', schema=None) as batch_op:
        batch_op.drop_column('createdAt')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
