"""Add motion readings

Revision ID: 814032faa57c
Revises: 3e805a76f9ef
Create Date: 2025-04-24 00:33:24.534213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814032faa57c'
down_revision = '3e805a76f9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motion_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('motion_file_id', sa.Integer(), nullable=False),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['motion_file_id'], ['motion_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motion_readings')
    # ### end Alembic commands ###
