"""Motion files need names

Revision ID: 856817febc15
Revises: 0ec778454eec
Create Date: 2025-04-02 15:38:09.241988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856817febc15'
down_revision = '0ec778454eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motion_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motion_files', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
