"""Add devices

Revision ID: 96494532f800
Revises: f2764d6ff9dd
Create Date: 2025-03-31 14:34:30.163270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96494532f800'
down_revision = 'f2764d6ff9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
