"""Add patient physician relation table

Revision ID: ca27853b4be3
Revises: f00e432f7d44
Create Date: 2025-04-05 16:27:19.163872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca27853b4be3'
down_revision = 'f00e432f7d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_physicians',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('physician_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'physician_id'),
    sa.UniqueConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_physicians')
    # ### end Alembic commands ###
