"""Combine users

Revision ID: f00e432f7d44
Revises: 96494532f800
Create Date: 2025-04-02 16:14:41.012266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00e432f7d44'
down_revision = '96494532f800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_physician', sa.Boolean(), nullable=False),
    sa.Column('is_patient', sa.Boolean(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['sender'], ['id'])

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['patient_id'])
        batch_op.drop_constraint('chats_physician_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('chats_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['physician_id'], ['id'])

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint('devices_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['patient_id'], ['id'])
    
    op.drop_table('patients')
    op.drop_table('physicians')
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('physician_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('devices_patient_id_fkey', 'patients', ['patient_id'], ['id'])

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chats_patient_id_fkey', 'patients', ['patient_id'], ['id'])
        batch_op.create_foreign_key('chats_physician_id_fkey', 'physicians', ['physician_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('users')
    # ### end Alembic commands ###
